[package]
name = "blockchain_template_generator"
version = "0.1.0"
edition = "2021"
authors = ["Danila <meltan1199@gmail.com>"]
description = "A Rust program used for mining on the Vanilla Coin Blockchain."

[dependencies]
blake3 = "1.3.3"
rand = "0.8.5"